name: Run Pytest on Merge to Master
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      # Use linux container with uv preinstalled
      image: ghcr.io/astral-sh/uv:debian
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Python
        run: |
          uv python install 3.12
      - name: Install dependencies with uv
        run: |
          uv sync
      - name: Run Pytest
        run: |
          uv run pytest
